### ISSUE TITLE
codify scenario weightings for a test run

### ISSUE THREAD

**Issue by willkg** [mozilla-services/antenna-loadtests#17]
One of the things we want to do is re-weight the scenarios depending on the load test type and what we're trying to answer. It'd be great for reproducibility and documentation purposes if we could codify the weights used along with the other test parameters in a single file.

One way to do that would be to move the scenario weightings to env vars thus exposing them in a way that lets us codify them in a `loads.json` file.

Doing this should be straight-forward. It'd involve changing these lines:

```
@scenario(20)
def test_...():
```

to something like this:

```
def weighted_scenario(fun):
    fun_name = fun.__name__  # or whatever it is
    weighting = int(os.environ.get(fun_name, 20))

    return scenario(weighting)(fun)


@weighted_scenario
def test_something(...):
    ...
```

Are there other ways to do this?

**Comment by m8ttyB** [comment]
cc @rpappalax

**Comment by rpappalax** [comment]
@willkg sure, we could add a key for "additional_command_args" into the "steps" object of the loads.json file and pass in the weights dynamically that way.  It would look something like this:
https://github.com/loads/loads-broker/blob/b5e967bb8a85523836739ab9181b98e0bf4f71a9/loadsbroker/tests/request.json#L57
@tarekziade, we do this with ap-loadtester, but is there a better way to do this for molotov? (aka: specifying the test weights in loads.json?)

**Comment by willkg** [comment]
Closing this out because we're not going to do this.
