### ISSUE TITLE
Update ailoads for molotov 

### ISSUE THREAD

**Issue by m8ttyB** [mozilla-services/antenna-loadtests#9]

**Comment by willkg** [comment]
I started looking into this and targeting molotov 0.3 which is the most recent release on pypi. I've got it working, but it's still using requests which is synchronous.

I'll rework the requests code to use aiohttp. It's possible we could hit an issue with that--I forget what weird things the network code does.

I have no idea how this affects running the loadtests across multiple nodes. So I'll just do the work and stick it in a branch and let y'alls look at that aspect of it.

**Comment by m8ttyB** [comment]
Work for this is happening here, pr #21

**Comment by m8ttyB** [comment]
Work for this is complete. Closing
